### ISSUE TITLE
nbdev_clean pre-commit hook doesn't clean all metadata

### ISSUE THREAD

**Issue by pep-sanwer** [AnswerDotAI/nbdev#1152]
Thank you @seeM for adding this awesome feature.

I am currently seeing an issue where the nbdev_clean pre-commit hook doesn't clean all cell meta-data (specifically execute times -- "recordTiming": true in Notebook settings - JupyterLab):
![image](https://user-images.githubusercontent.com/112018564/194964144-0f172e08-d06b-4bef-a9bd-7f1fd1848e8b.png)

If this is expected behavior for the hook, would it be possible to pass custom cell tags as a parameter to the pre-commit hook?

**Comment by dleen** [comment]
Are you executing the hook by `pre-commit run` or are you staging the change and committing? When I was experimenting with the hooks I didn't realise that it essentially does a `git stash` before running the hook and `git stash pop` afterwards so that any unstaged changes don't get cleaned. Maybe this is happening to you?

**Comment by dleen** [comment]
Is it possible that it's not finding the notebooks because they aren't in the `nbs_path` dir or whatever yours is configured to be? See: https://github.com/fastai/nbdev/blob/master/settings.ini#L52

In one of my repos (private unfortunately) I have the majority of notebooks in the `nbs` folder like the link above but I have some in a sibling folder to `nbs` called `scheduled` and I updated the `.pre-commit-config.yaml` to be:

```
repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.3.7
  hooks:
  - id: nbdev_clean
  - id: nbdev_clean
    args: [--fname=scheduled]
  - id: nbdev_export
```
